#:schema node_modules/wrangler/config-schema.json
name = "nuxiox"
main = "./.output/server/index.mjs"
compatibility_date = "2024-11-01"

# This defines where your static assets (images, JS, CSS) live after building
assets = { directory = "./.output/public/", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "nuxiox_db"
database_id = "6e9f75b8-eb61-4f10-ab0a-35592480dc1d"
migrations_dir = "./server/database/migrations"

[[kv_namespaces]]
binding = "MEDIA_KV"
id = "797e4c46be7b4a68877160acd39efc73"
preview_id = "797e4c46be7b4a68877160acd39efc73"