// Auto-generated by scripts/generate-sections-manifest.ts — do not edit
export const SECTIONS_MANIFEST: SectionItem[] = [
  {"id":"About","label":"About","type":"section"},
  {"id":"Blog","label":"Blog","type":"section"},
  {"id":"Contact","label":"Contact","type":"section"},
  {"id":"Footer","label":"Footer","type":"footer"},
  {"id":"Hero","label":"Hero","type":"section"},
  {"id":"Hours","label":"Hours","type":"section"},
  {"id":"Navbar","label":"Navbar","type":"navbar"},
  {"id":"Portfolio","label":"Portfolio","type":"section"},
  {"id":"Promotions","label":"Promotions","type":"section"},
  {"id":"Results","label":"Results","type":"section"},
  {"id":"Service","label":"Service","type":"section"},
  {"id":"Services","label":"Services","type":"section"},
  {"id":"Team","label":"Team","type":"section"},
  {"id":"Technology","label":"Technology","type":"section"},
  {"id":"Testimonial","label":"Testimonial","type":"section"},
  {"id":"Whyus","label":"Whyus","type":"section"}
]

type SectionItem = { id: string; label: string; type: 'section' | 'navbar' | 'footer' }
