#!/usr/bin/env tsx
/**
 * Nuxiox Theme Converter
 *
 * Takes a theme output folder (generated by an AI tool like Google Studio)
 * and bakes it into a fully working Nuxiox theme with all Nuxt-specific files.
 *
 * The AI should only create:
 *   - components/sections/*.vue
 *   - components/ui/BookingModal.vue (optional)
 *   - components/ui/ImageModal.vue (optional)
 *   - i18n/locales/{en,fa,ar}.json
 *   - assets/theme.css (optional)
 *
 * This script generates everything else: nuxt.config.ts, layouts, pages, etc.
 *
 * Usage:
 *   pnpm run convert-theme -- <name> <source-dir>
 *   pnpm run convert-theme -- mim-beauty ./ai-output/mim-beauty
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
import { injectDataI18n } from './inject-i18n.ts'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const THEMES_DIR = path.resolve(ROOT, 'packages/themes')

// ─── Helpers ──────────────────────────────────────────────────────────────

const C = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  cyan: '\x1b[36m',
}

function log(msg: string) {
  console.log(`${C.bold}${C.cyan}»${C.reset} ${msg}`)
}

function ok(msg: string) {
  console.log(`  ${C.green}✔${C.reset} ${msg}`)
}

function warn(msg: string) {
  console.log(`  ${C.yellow}⚠${C.reset} ${msg}`)
}

function err(msg: string) {
  console.log(`  ${C.red}✖${C.reset} ${msg}`)
}

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true })
}

function copyFile(src: string, dest: string) {
  ensureDir(path.dirname(dest))
  fs.copyFileSync(src, dest)
  ok(`Copied ${path.relative(ROOT, src)} → ${path.relative(ROOT, dest)}`)
}

function writeFile(filePath: string, content: string) {
  ensureDir(path.dirname(filePath))
  fs.writeFileSync(filePath, content, 'utf-8')
  ok(`Generated ${path.relative(ROOT, filePath)}`)
}

/** Recursively collect all dotted key paths from a nested object. */
function flattenKeys(obj: Record<string, any>, prefix = ''): string[] {
  const result: string[] = []
  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${key}` : key
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      result.push(...flattenKeys(value, fullKey))
    } else {
      result.push(fullKey)
    }
  }
  return result
}

// ─── Templates ────────────────────────────────────────────────────────────

function nuxtConfigTemplate(name: string, databaseLayer: string): string {
  return `// Auto-generated by scripts/convert-theme.ts
export default defineNuxtConfig({
  extends: ['../../base', '../../databases/${databaseLayer}'],

  css: ['~~/packages/themes/${name}/app/assets/theme.css'],

  modules: ['@nuxtjs/i18n'],

  nitro: {
    preset: 'cloudflare-module',
  },

  i18n: {
    locales: [
      { code: 'fa', file: 'fa.json' },
      { code: 'en', file: 'en.json' },
      { code: 'ar', file: 'ar.json' },
    ],
  },

  compatibilityDate: '2025-07-15',
})
`
}

function appConfigTemplate(name: string, description: string): string {
  return `// Auto-generated by scripts/convert-theme.ts
export default defineAppConfig({
  theme: {
    name: '${name}',
    description: '${description}',
  },
})
`
}

function layoutDefaultTemplate(hasBookingModal: boolean, hasImageModal: boolean): string {
  const modalLines: string[] = []
  if (hasBookingModal) {
    modalLines.push(`    <BookingModal v-if="modalStore.isBookingOpen" :is-open="modalStore.isBookingOpen" @close="modalStore.closeBooking()" />`)
  }
  if (hasImageModal) {
    modalLines.push(`    <ImageModal v-if="modalStore.selectedImage" :image-url="modalStore.selectedImage" @close="modalStore.closeImage()" />`)
  }
  const modalImports: string[] = []
  if (hasBookingModal) modalImports.push(`import BookingModal from '../components/ui/BookingModal.vue'`)
  if (hasImageModal) modalImports.push(`import ImageModal from '../components/ui/ImageModal.vue'`)

  return `<script setup lang="ts">
import Navbar from '../components/sections/Navbar.vue'
import Footer from '../components/sections/Footer.vue'
import { useModalStore } from '~~/packages/base/app/stores/modal'
${modalImports.join('\n')}

const { settings } = useSiteSettings()
const layoutOverrides = useLayoutOverrides()
const { locale } = useI18n()
const modalStore = useModalStore()

const dirAttr = computed(() => (locale.value === 'fa' || locale.value === 'ar') ? 'rtl' : 'ltr')

useHead(() => ({
  htmlAttrs: {
    dir: dirAttr.value,
    lang: locale.value,
    class: dirAttr.value,
  },
}))
</script>

<template>
  <div class="min-h-screen flex flex-col">
    <AdminToolbar />
    <Navbar
      v-if="!layoutOverrides.hideNavbar"
      :menus="settings?.navbar?.menus"
      :dark-logo="settings?.navbar?.darkLogo"
      :light-logo="settings?.navbar?.lightLogo"
      :info="settings?.navbar?.info"
    />

    <main class="flex-1">
      <slot />
    </main>

    <Footer
      v-if="!layoutOverrides.hideFooter"
      :menus="settings?.footer?.menus"
      :dark-logo="settings?.footer?.darkLogo"
      :light-logo="settings?.footer?.lightLogo"
      :info="settings?.footer?.info"
    />

${modalLines.join('\n')}
  </div>
</template>
`
}

function pageIndexTemplate(): string {
  return `<script setup lang="ts">
import type { HomeBuilder } from '~~/packages/base/types/page-builder'
import { defaultHomeBuilder } from '~~/packages/base/utils/page-builder'

const modules = import.meta.glob('../components/sections/*.vue')
const components: Record<string, Component> = {}

for (const path in modules) {
  const loader = modules[path]
  if (!loader) continue
  const fileName = path.split('/').pop()
  if (!fileName) continue
  const name = fileName.replace('.vue', '')
  components[name] = defineAsyncComponent(() => loader().then((m: any) => m.default))
}

const { data } = await useFetch<HomeBuilder>('/api/home-builder/public', {
  default: () => structuredClone(defaultHomeBuilder),
})
const builder = computed(() => data.value ?? structuredClone(defaultHomeBuilder))
const layoutOverrides = useLayoutOverrides()

watch(
  () => builder.value.sections,
  (sections) => {
    layoutOverrides.value.hideNavbar = sections.some((section) => section.type === 'navbar')
    layoutOverrides.value.hideFooter = sections.some((section) => section.type === 'footer')
  },
  { immediate: true }
)

onBeforeUnmount(() => {
  layoutOverrides.value.hideNavbar = false
  layoutOverrides.value.hideFooter = false
})
</script>

<template>
  <div>
    <component v-for="section in builder.sections" :is="components[section.sectionId]" :key="section.uid" />
  </div>
</template>
`
}

function pageSlugTemplate(): string {
  return `<script setup lang="ts">
import type { PageBlock } from '~~/packages/base/types/page-builder'

const modules = import.meta.glob('../components/sections/*.vue')
const components: Record<string, Component> = {}

for (const path in modules) {
  const loader = modules[path]
  if (!loader) continue
  const fileName = path.split('/').pop()
  if (!fileName) continue
  const name = fileName.replace('.vue', '')
  components[name] = defineAsyncComponent(() => loader().then((m: any) => m.default))
}

const route = useRoute()
const slug = computed(() => route.params.slug as string)

interface PageRecord {
  id: number
  title: string
  slug: string
  seo?: any
  builder: {
    version: number
    blocks: PageBlock[]
  }
}

const { data, error } = await useFetch<PageRecord>(() => \`/api/pages/public/\${slug.value}\`)
if (error.value) throw createError({ statusCode: 404, statusMessage: 'Page not found' })

const page = computed(() => {
  const raw = data.value
  if (!raw) return null
  const parsed = structuredClone(raw) as any
  if (typeof parsed.builder === 'string') {
    try {
      const b = JSON.parse(parsed.builder)
      parsed.builder = typeof b === 'object' && b !== null ? b : { version: 1, blocks: [] }
    } catch { parsed.builder = { version: 1, blocks: [] } }
  }
  if (typeof parsed.seo === 'string') {
    try {
      const s = JSON.parse(parsed.seo)
      parsed.seo = typeof s === 'object' && s !== null ? s : {}
    } catch { parsed.seo = {} }
  }
  return parsed
})

const layoutOverrides = useLayoutOverrides()

watch(
  () => page.value?.builder?.blocks,
  (blocks) => {
    if (!blocks) return
    layoutOverrides.value.hideNavbar = blocks.some((b: any) => b.type === 'navbar')
    layoutOverrides.value.hideFooter = blocks.some((b: any) => b.type === 'footer')
  },
  { immediate: true }
)

onBeforeUnmount(() => {
  layoutOverrides.value.hideNavbar = false
  layoutOverrides.value.hideFooter = false
})

useHead(() => {
  const seo = page.value?.seo || {}
  return {
    title: seo.title || page.value?.title || '',
    meta: [
      seo.description ? { name: 'description', content: seo.description } : undefined,
    ].filter(Boolean),
  }
})
</script>

<template>
  <div>
    <template v-if="page?.builder?.blocks">
      <template v-for="block in page.builder.blocks" :key="block.uid">
        <div v-if="block.type === 'text'" v-html="block.content" />
        <component v-else-if="block.sectionId && components[block.sectionId]" :is="components[block.sectionId]" />
      </template>
    </template>
    <div v-else class="py-24 text-center">
      <p>{{ $t('cms.notFound') }}</p>
    </div>
  </div>
</template>
`
}

function blogIndexTemplate(): string {
  return `<script setup lang="ts">
const { data } = await useFetch<any>('/api/blog/posts')
const posts = computed(() => data.value?.items ?? [])
const categories = computed(() => data.value?.categories ?? [])

const searchQuery = ref('')
const selectedCategory = ref('ALL')

const filteredPosts = computed(() => {
  return posts.value.filter((post: any) => {
    const matchesSearch = !searchQuery.value
      || post.title.toLowerCase().includes(searchQuery.value.toLowerCase())
      || (post.excerpt && post.excerpt.toLowerCase().includes(searchQuery.value.toLowerCase()))
    const matchesCategory = selectedCategory.value === 'ALL' || post.category === selectedCategory.value
    return matchesSearch && matchesCategory
  })
})
const categorySlugs = computed(
  () => new Map((categories.value ?? []).map((c: any) => [c.name, c.slug]))
)
</script>

<template>
  <div class="py-24">
    <div class="max-w-7xl mx-auto px-6 sm:px-12 space-y-12">
      <div class="text-center max-w-3xl mx-auto">
        <h1 class="text-4xl sm:text-6xl font-bold">{{ $t('blog.title') }}</h1>
        <p class="text-sm mt-2">{{ $t('blog.subtitle') }}</p>
      </div>

      <div class="flex flex-col sm:flex-row items-center gap-4 max-w-3xl mx-auto">
        <input v-model="searchQuery" :placeholder="$t('blog.searchPlaceholder')" class="w-full input input-bordered" />
        <select v-model="selectedCategory" class="select select-bordered">
          <option value="ALL">{{ $t('blog.allCategories') }}</option>
          <option v-for="c in categories" :key="c.slug" :value="c.name">{{ c.name }}</option>
        </select>
      </div>

      <div v-if="filteredPosts.length > 0" class="grid grid-cols-1 md:grid-cols-3 gap-8">
        <article v-for="post in filteredPosts" :key="post.id" class="card">
          <img v-if="post.featuredImage" :src="post.featuredImage" :alt="post.title" class="w-full h-52 object-cover" />
          <div class="p-6">
            <h2 class="text-lg font-bold">{{ post.title }}</h2>
            <p v-if="post.excerpt" class="text-sm mt-2">{{ post.excerpt }}</p>
            <NuxtLink :to="$localePath(\`/blog/\${post.slug}\`)" class="btn btn-sm btn-primary mt-4">
              {{ $t('blog.readMore') }}
            </NuxtLink>
          </div>
        </article>
      </div>
      <div v-else class="text-center py-16">{{ $t('blog.notFound') }}</div>
    </div>
  </div>
</template>
`
}

function blogShowTemplate(): string {
  return `<script setup lang="ts">
const route = useRoute()
const slug = computed(() => route.params.slug as string)

const { data } = await useFetch<any>(() => \`/api/blog/posts/\${slug.value}\`)
const post = computed(() => data.value?.post ?? null)
const comments = ref(data.value?.comments ?? [])

const commentAuthor = ref('')
const commentText = ref('')

async function handleCommentSubmit(e: Event) {
  e.preventDefault()
  if (!commentText.value) return
  try {
    await $fetch(\`/api/blog/posts/\${slug.value}/comments\`, {
      method: 'POST',
      body: { authorName: commentAuthor.value || undefined, content: commentText.value },
    })
    comments.value.unshift({ id: Date.now(), authorName: commentAuthor.value || $t('blog.yourName'), content: commentText.value, createdAt: new Date().toISOString(), likeCount: 0, replies: [] })
    commentAuthor.value = ''
    commentText.value = ''
  } catch (e) {
    // Comment failed — silently keep local state
  }
}

useHead(() => ({
  title: post.value?.title || '',
}))
</script>

<template>
  <div class="py-24">
    <div class="max-w-4xl mx-auto px-6 sm:px-12 space-y-10">
      <NuxtLink :to="$localePath('/blog')" class="text-sm font-bold hover:underline">
        &larr; {{ $t('blog.readMore') }}
      </NuxtLink>

      <div v-if="post">
        <h1 class="text-3xl sm:text-5xl font-bold">{{ post.title }}</h1>
        <img v-if="post.featuredImage" :src="post.featuredImage" :alt="post.title" class="w-full h-96 object-cover rounded-2xl my-8" />
        <div v-html="post.content" class="prose max-w-none" />
      </div>

      <div class="border-t pt-8 space-y-6">
        <h2 class="text-2xl font-bold">{{ $t('blog.comments') }} ({{ comments.length }})</h2>

        <form @submit="handleCommentSubmit" class="space-y-4">
          <input v-model="commentAuthor" :placeholder="$t('blog.yourName')" class="input input-bordered w-full" />
          <textarea v-model="commentText" :placeholder="$t('blog.yourComment')" class="textarea textarea-bordered w-full" rows="4" required></textarea>
          <button type="submit" class="btn btn-primary">{{ $t('blog.postComment') }}</button>
        </form>

        <div v-for="comment in comments" :key="comment.id" class="border p-4 rounded-xl space-y-1">
          <div class="flex items-center justify-between text-sm">
            <span class="font-bold">{{ comment.authorName || $t('blog.yourName') }}</span>
            <span class="text-gray-400">{{ comment.createdAt }}</span>
          </div>
          <p class="text-sm">{{ comment.content }}</p>
        </div>
      </div>
    </div>
  </div>
</template>
`
}

// ─── Main Converter ──────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2).filter(a => a !== '--')

  if (args.length < 2) {
    console.log(`
${C.bold}Usage:${C.reset} pnpm run convert-theme -- <theme-name> <source-dir> [options]

${C.bold}Arguments:${C.reset}
  theme-name     Name of the theme (e.g. 'mim-beauty')
  source-dir     Path to the AI-generated theme folder

${C.bold}Options:${C.reset}
  --db=cloudflare  Database layer (default: cloudflare)
  --db=normal      Use MySQL/normal database layer
  --description   Theme description for app.config.ts

${C.bold}Example:${C.reset}
  pnpm run convert-theme -- my-theme ./ai-output/my-theme --description "My theme"
`)
    process.exit(1)
  }

  const themeName = args[0]
  const sourceDir = path.resolve(args[1])
  const dbLayer = args.find(a => a.startsWith('--db='))?.split('=')[1] || 'cloudflare'
  const description = args.find(a => a.startsWith('--description='))?.split('=')[1] || `${themeName} theme`

  // ── Validate source directory ───────────────────────────────────────

  if (!fs.existsSync(sourceDir)) {
    err(`Source directory not found: ${sourceDir}`)
    process.exit(1)
  }

  const sectionsDir = path.resolve(sourceDir, 'components/sections')
  const i18nDir = path.resolve(sourceDir, 'i18n/locales')
  const uiDir = path.resolve(sourceDir, 'components/ui')
  const assetsDir = path.resolve(sourceDir, 'assets')

  if (!fs.existsSync(sectionsDir)) {
    err(`Source directory must contain components/sections/`)
    process.exit(1)
  }

  // ── Create theme directory ──────────────────────────────────────────

  const themeDir = path.resolve(THEMES_DIR, themeName)
  const themeAppDir = path.resolve(themeDir, 'app')

  if (fs.existsSync(themeDir)) {
    warn(`Theme directory already exists: ${themeName}`)
    warn(`Files will be overwritten. Press Ctrl+C to cancel.`)
  }

  // ── Copy sections ──────────────────────────────────────────────────

  log(`Copying section components...`)
  const sectionFiles = fs.readdirSync(sectionsDir).filter(f => f.endsWith('.vue'))
  for (const file of sectionFiles) {
    const srcPath = path.resolve(sectionsDir, file)
    const destPath = path.resolve(themeAppDir, 'components/sections', file)
    let content = fs.readFileSync(srcPath, 'utf-8')
    // Fix common import mistakes in AI-generated sections
    // 1. Wrong modal store path (relative instead of base-layer absolute)
    content = content.replace(
      /from\s+['\"]\.\.\/\.\.\/stores\/modal['\"]/g,
      "from '~~/packages/base/app/stores/modal'",
    )
    content = content.replace(
      /from\s+['\"]\.\.\/stores\/modal['\"]/g,
      "from '~~/packages/base/app/stores/modal'",
    )
    // 2. Fix refs without .value inside array literals used in event handlers.
    // AI often produces: `const videos = [video1Ref, video2Ref]` then uses
    // `videos[next]!.currentTime`. The refs must be unwrapped at declaration:
    // `const videos = [video1Ref.value, video2Ref.value]`.
    content = content.replace(
      /(const\s+\w+\s*=\s*\[)([^\]]*Ref,?[^\]]*)(\])/g,
      (match, prefix, body, suffix) => {
        // Only touch arrays where every element is a Ref variable
        const items = body.split(',').map((s) => s.trim()).filter(Boolean)
        if (items.length && items.every((it) => /^\w+Ref\s*$/.test(it))) {
          const fixed = items.map((it) => `${it}.value`).join(', ')
          warn(`  Unwrapped refs in array: ${body.trim()} → ${fixed}`)
          return `${prefix}${fixed}${suffix}`
        }
        return match
      }
    )
    // 3. Fix malformed Tailwind classes in fa-icon syntax
    // AI sometimes produces: `fa-[#C5A059]` as a class instead of `text-[#C5A059]`
    content = content.replace(
      /fa-\[#[A-Fa-f0-9]{3,6}\]/g,
      (match) => {
        const color = match.match(/#[A-Fa-f0-9]{3,6}/)?.[0] || '#C5A059'
        warn(`  Fixed malformed class '${match}' → 'text-[${color}]' in ${file}`)
        return `text-[${color}]`
      }
    )
    // 4. Warn about hardcoded text strings (potential i18n misses)
    const hardcodedTexts = content.match(/>[^<]{3,}[^<]*</g)
    if (hardcodedTexts) {
      const nonI18nTexts = hardcodedTexts.filter(
        (t) => !t.includes('{{') && !t.includes('$t(') && !t.includes('v-') && !t.includes('</')
      )
      if (nonI18nTexts.length > 0) {
        for (const text of nonI18nTexts.slice(0, 3)) {
          warn(`  Possible hardcoded text in ${file}: "${text.slice(1, 60)}"`)
        }
      }
    }

    // 5. Check Navbar/Footer props are actually used in the template
    if (file === 'Navbar.vue' || file === 'Footer.vue') {
      const template = content.match(/<template>[\s\S]*<\/template>/)?.[0] || ''
      const hasMenusProp = content.includes('menus?:') || content.includes('menus:')
      const hasLogoProp = content.includes('darkLogo?:') || content.includes('darkLogo:')
      const hasInfoProp = content.includes('info?:') || content.includes('info:')
      const usesMenus = template.includes('menus') || content.includes('props.menus')
      const usesLogo = template.includes('darkLogo') || template.includes('lightLogo') || content.includes('props.darkLogo') || content.includes('props.lightLogo')
      const usesInfo = template.includes('info') || content.includes('props.info')

      if (hasMenusProp && !usesMenus) {
        warn(`  ${file}: 'menus' prop is defined but never used in the template. Iterate over it with v-for to render admin-configured nav links.`)
      }
      if (hasLogoProp && !usesLogo) {
        warn(`  ${file}: 'darkLogo'/'lightLogo' props are defined but never used. Render them as <img> with a text fallback.`)
      }
      if (hasInfoProp && !usesInfo) {
        warn(`  ${file}: 'info' prop is defined but never used. Render its items dynamically for contact details.`)
      }
    }

    // 6. Fix RTL/LTR direction — convert hardcoded text-right/text-left to use Tailwind variants
    content = content.replace(
      /(?<![-\w])text-right(?=[\s"'`}])/g,
      'ltr:text-left rtl:text-right'
    )
    // Fix margin-left → ltr:ml-* rtl:mr-*
    content = content.replace(
      /(?<![-\w])ml-(\d+(?:\.\d+)?(?:\/\d+)?(?![-\w]))/g,
      'ltr:ml-$1 rtl:mr-$1'
    )
    // Fix margin-right → ltr:mr-* rtl:ml-*
    content = content.replace(
      /(?<![-\w])mr-(\d+(?:\.\d+)?(?:\/\d+)?(?![-\w]))/g,
      'ltr:mr-$1 rtl:ml-$1'
    )

        // 7. Inject localeHref helper into Navbar/Footer for locale-aware menu links
            if ((file === 'Navbar.vue' || file === 'Footer.vue') && !content.includes('localeHref')) {
              // Replace `:href="item.href"` with `:href="localeHref(item.href)"` in v-for="item in menus" loops
              content = content.replace(
                /(:href=")item\.href(")/g,
                '$1localeHref(item.href)$2'
              )
              // Inject the localeHref helper function before </script>
              const scriptEnd = content.lastIndexOf('</script>')
              if (scriptEnd !== -1) {
                const helper = `

        const localePath = useLocalePath()

        // Locale-prefix internal paths, leave external/anchor links as-is
        function localeHref(href: string) {
          if (!href || href.startsWith('#') || href.startsWith('http://') || href.startsWith('https://') || href.startsWith('//')) {
            return href
          }
          return localePath(href)
        }
        `
        content = content.slice(0, scriptEnd) + helper + content.slice(scriptEnd)
        ok(`  Added localeHref helper to ${file} for locale-aware menu links`)
              }
            }

            // 8. Fix video elements missing opacity transitions (Hero.vue video switching)
            if (content.includes('@ended') && content.includes('opacity-') && !content.includes('transition-opacity')) {
              content = content.replace(
                /(class="[^"]*opacity-\d+[^"]*")/g,
                (match) => {
                  if (match.includes('transition-opacity')) return match
                  return match.replace('"', ' transition-opacity duration-1000"')
                }
              )
              ok(`  Added transition-opacity to video elements in ${file}`)
            }

            // 9. Auto-add data-i18n attributes to elements using $t('key')
            content = injectDataI18n(content)

            // 10. Auto-add data-nuxiox-img attributes to <img> tags
            // Uses the alt text or filename as a key hint
            if (content.includes('<img')) {
              content = content.replace(
                /<img(\s[^>]*?)\s*\/?>/g,
                (match, attrs) => {
                  // Skip if already has data-nuxiox-img
                  if (attrs.includes('data-nuxiox-img=')) return match
                  // Skip if it's a dynamic src (v-bind or :)
                  if (attrs.includes(':src') || attrs.includes('v-bind:src')) return match
                  // Extract a key from alt text, or generate from filename
                  const altMatch = attrs.match(/alt=["']([^"']+)["']/)
                  const srcMatch = attrs.match(/src=["']([^"']+)["']/)
                  let key = 'image'
                  if (altMatch) {
                    key = altMatch[1].toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '') || 'image'
                  } else if (srcMatch) {
                    const filename = srcMatch[1].split('/').pop()?.split('.')[0] || 'image'
                    key = filename.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '') || 'image'
                  }
                  return '<img' + attrs.replace('/>', '>').replace(' />', '>') + ' data-nuxiox-img="' + key + '">'
                }
              )
            }

            ensureDir(path.dirname(destPath))
    fs.writeFileSync(destPath, content, 'utf-8')
    ok(`Copied ${path.relative(ROOT, srcPath)} → ${path.relative(ROOT, destPath)}`)
  }
  ok(`Found ${sectionFiles.length} section components`)

  // ── Copy i18n files ────────────────────────────────────────────────

  log(`Copying i18n locale files...`)
  // i18n files go to theme root (NOT inside app/) — Nuxt layers resolve them
  // from the layer's own i18n/ directory
  const themeI18nDir = path.resolve(themeDir, 'i18n/locales')
  if (fs.existsSync(i18nDir)) {
    const localeFiles = fs.readdirSync(i18nDir).filter(f => f.endsWith('.json'))
    for (const file of localeFiles) {
      const srcPath = path.resolve(i18nDir, file)
      const destPath = path.resolve(themeI18nDir, file)
      // Read, replace @ with [at] to avoid vue-i18n linked-message parsing
      let content = fs.readFileSync(srcPath, 'utf-8')
      content = content.replace(/@(?=[a-zA-Z])/g, '[at]')
      ensureDir(path.dirname(destPath))
      fs.writeFileSync(destPath, content, 'utf-8')
      ok(`Copied + escaped @ in ${file}`)
    }
    ok(`Found ${localeFiles.length} locale files`)

    // ── i18n key validation ──────────────────────────────────────────
    log(`Validating i18n keys across locales...`)
    const localeData: Record<string, Set<string>> = {}
    for (const file of localeFiles) {
      const raw = fs.readFileSync(path.resolve(themeI18nDir, file), 'utf-8')
      try {
        const parsed = JSON.parse(raw) as Record<string, any>
        const keys = flattenKeys(parsed)
        localeData[file.replace('.json', '')] = new Set(keys)
      } catch (e) {
        warn(`Could not parse ${file}: ${e}`)
      }
    }
    const localeNames = Object.keys(localeData)
    if (localeNames.length > 1) {
      const baseKeys = localeData[localeNames[0]]
      for (let i = 1; i < localeNames.length; i++) {
        const name = localeNames[i]
        const keys = localeData[name]
        const missing = [...baseKeys].filter(k => !keys.has(k))
        const extra = [...keys].filter(k => !baseKeys.has(k))
        if (missing.length > 0) {
          warn(`${name}.json is missing ${missing.length} key(s): ${missing.slice(0, 10).join(', ')}${missing.length > 10 ? '...' : ''}`)
        }
        if (extra.length > 0) {
          warn(`${name}.json has ${extra.length} extra key(s) not in other locales: ${extra.slice(0, 5).join(', ')}${extra.length > 5 ? '...' : ''}`)
        }
      }
      ok(`i18n keys validated across ${localeNames.length} locales`)
    }
  } else {
    warn(`No i18n/locales/ directory found — you'll need to add translations manually`)
  }

  // ── Copy UI components ─────────────────────────────────────────────

  log(`Copying UI components...`)
  let hasBookingModal = false
  let hasImageModal = false
  if (fs.existsSync(uiDir)) {
    const uiFiles = fs.readdirSync(uiDir).filter(f => f.endsWith('.vue'))
    for (const file of uiFiles) {
      copyFile(
        path.resolve(uiDir, file),
        path.resolve(themeAppDir, 'components/ui', file),
      )
      if (file === 'BookingModal.vue') hasBookingModal = true
      if (file === 'ImageModal.vue') hasImageModal = true
    }
    if (uiFiles.length > 0) ok(`Found ${uiFiles.length} UI components`)
  }

  // ── Copy assets ────────────────────────────────────────────────────

  log(`Copying assets...`)
  if (fs.existsSync(assetsDir)) {
    const assetFiles = fs.readdirSync(assetsDir)
    for (const file of assetFiles) {
      copyFile(
        path.resolve(assetsDir, file),
        path.resolve(themeAppDir, 'assets', file),
      )
    }
    if (assetFiles.length > 0) ok(`Found ${assetFiles.length} asset files`)

    // Inject RTL arrow icon CSS into theme.css if it exists
    const themeCssPath = path.resolve(themeAppDir, 'assets/theme.css')
    if (fs.existsSync(themeCssPath)) {
      let css = fs.readFileSync(themeCssPath, 'utf-8')
      if (!css.includes('RTL-aware arrow icons')) {
        css += `

/* RTL-aware arrow icons — flip direction in RTL mode */
[dir="rtl"] .fa-arrow-left,
[dir="rtl"] .fa-arrow-right,
[dir="rtl"] .fa-chevron-left,
[dir="rtl"] .fa-chevron-right,
[dir="rtl"] .fa-angle-left,
[dir="rtl"] .fa-angle-right {
  transform: scaleX(-1);
}
`
        fs.writeFileSync(themeCssPath, css, 'utf-8')
        ok('Added RTL arrow icon flip CSS to theme.css')
      }
    }
  }

  // ── Generate Nuxt-specific files ───────────────────────────────────

  log(`Generating Nuxt-specific files...`)

  // nuxt.config.ts
  writeFile(
    path.resolve(themeDir, 'nuxt.config.ts'),
    nuxtConfigTemplate(themeName, dbLayer),
  )

  // app.config.ts
  writeFile(
    path.resolve(themeAppDir, 'app.config.ts'),
    appConfigTemplate(themeName, description),
  )

  // layouts/default.vue
  writeFile(
    path.resolve(themeAppDir, 'layouts/default.vue'),
    layoutDefaultTemplate(hasBookingModal, hasImageModal),
  )

  // pages/index.vue
  writeFile(
    path.resolve(themeAppDir, 'pages/index.vue'),
    injectDataI18n(pageIndexTemplate()),
  )

  // pages/[slug].vue
  writeFile(
    path.resolve(themeAppDir, 'pages/[slug].vue'),
    injectDataI18n(pageSlugTemplate()),
  )

  // pages/blog/index.vue
  writeFile(
    path.resolve(themeAppDir, 'pages/blog/index.vue'),
    injectDataI18n(blogIndexTemplate()),
  )

  // pages/blog/[slug].vue
  writeFile(
    path.resolve(themeAppDir, 'pages/blog/[slug].vue'),
    injectDataI18n(blogShowTemplate()),
  )

  // ── Write root nuxt.config.ts to point to the new theme ────────────

  log(`Updating root nuxt.config.ts to point to the new theme...`)
  const rootConfigPath = path.resolve(ROOT, 'nuxt.config.ts')
  let rootConfig = fs.readFileSync(rootConfigPath, 'utf-8')
  rootConfig = rootConfig.replace(
    /extends:\s*\[[^\]]*\]/,
    `extends: ['./packages/themes/${themeName}']`,
  )
  fs.writeFileSync(rootConfigPath, rootConfig, 'utf-8')
  ok(`Root nuxt.config.ts now points to ${themeName}`)

  // ── Summary ────────────────────────────────────────────────────────

  console.log(`
${C.bold}${C.green}✅ Theme conversion complete!${C.reset}

${C.bold}Theme:${C.reset}       ${themeName}
${C.bold}Location:${C.reset}    ${themeDir}
${C.bold}Database:${C.reset}    ${dbLayer}

${C.bold}Generated files:${C.reset}
  ${sectionFiles.length} section components
  ${themeDir}/nuxt.config.ts
  ${themeAppDir}/app.config.ts
  ${themeAppDir}/layouts/default.vue
  ${themeAppDir}/pages/index.vue
  ${themeAppDir}/pages/[slug].vue
  ${themeAppDir}/pages/blog/index.vue
  ${themeAppDir}/pages/blog/[slug].vue

${C.bold}Next steps:${C.reset}
  1. Run ${C.cyan}pnpm run build${C.reset} to verify the theme compiles
  2. Run ${C.cyan}pnpm run dev${C.reset} to preview the theme
  3. If you need to add more sections, put them in:
     ${C.dim}${themeAppDir}/components/sections/${C.reset}
`)
}

main()