// scripts/generate-sections-manifest.ts
// Build-time section manifest generator.
// Scans the active theme's app/components/sections/ directory for .vue files
// and generates packages/base/server/utils/sections-manifest.gen.ts
// This file is then imported at runtime — no filesystem access needed on Cloudflare Workers.
//
// Run automatically via nitro:build:before hook in nuxt.config.ts,
// or manually: tsx scripts/generate-sections-manifest.ts

import { readFileSync, readdirSync, existsSync, writeFileSync } from 'node:fs'
import { resolve, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = resolve(fileURLToPath(import.meta.url), '..')
const ROOT = resolve(__dirname, '..')

function detectActiveThemeName(): string {
  try {
    const configPath = resolve(ROOT, 'nuxt.config.ts')
    const content = readFileSync(configPath, 'utf-8')
    const match = content.match(/extends:\s*\[[^\]]*['"]\.\/packages\/themes\/([^'"/]+)['"]/)
    if (match && match[1]) {
      return match[1]
    }
  } catch {
    // fall through
  }
  return process.env.NUXT_LAYER || 'dentist'
}

function toLabel(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[-_]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function detectType(id: string): 'section' | 'navbar' | 'footer' {
  const lower = id.toLowerCase()
  if (lower.includes('navbar')) return 'navbar'
  if (lower.includes('footer')) return 'footer'
  return 'section'
}

function generate(): void {
  const themeName = detectActiveThemeName()
  console.log(`[sections-manifest] Active theme: ${themeName}`)

  // Try packages/themes/<themeName>/app/components/sections/ first,
  // then fall back to packages/<themeName>/app/components/sections/
  const candidates = [
    resolve(ROOT, `packages/themes/${themeName}/app/components/sections`),
    resolve(ROOT, `packages/${themeName}/app/components/sections`),
  ]

  let sectionsDir: string | null = null
  for (const dir of candidates) {
    if (existsSync(dir)) {
      sectionsDir = dir
      break
    }
  }

  if (!sectionsDir) {
    console.warn(`[sections-manifest] ⚠ No sections directory found for theme "${themeName}"`)
    console.warn(`  Tried: ${candidates.join(', ')}`)
    // Write empty manifest so the API returns [ ]
    const output = `// Auto-generated by scripts/generate-sections-manifest.ts — do not edit
export const SECTIONS_MANIFEST: SectionItem[] = []
type SectionItem = { id: string; label: string; type: 'section' | 'navbar' | 'footer' }
`
    const outPath = resolve(ROOT, 'packages/base/server/utils/sections-manifest.gen.ts')
    writeFileSync(outPath, output, 'utf-8')
    console.log(`[sections-manifest] ✓ Wrote empty manifest to ${outPath}`)
    return
  }

  const entries = readdirSync(sectionsDir)
    .filter((entry) => entry.endsWith('.vue'))
    .map((entry) => {
      const id = basename(entry, '.vue')
      return JSON.stringify({ id, label: toLabel(id), type: detectType(id) })
    })
    .join(',\n  ')

  const output = `// Auto-generated by scripts/generate-sections-manifest.ts — do not edit
export const SECTIONS_MANIFEST: SectionItem[] = [
  ${entries}
]

type SectionItem = { id: string; label: string; type: 'section' | 'navbar' | 'footer' }
`

  const outPath = resolve(ROOT, 'packages/base/server/utils/sections-manifest.gen.ts')
  writeFileSync(outPath, output, 'utf-8')
  console.log(`[sections-manifest] ✓ Wrote manifest with ${entries.length} sections to ${outPath}`)
}

generate()