// scripts/sync-schema.ts
// Entry point for schema generation.
// Reads the canonical table definitions from packages/base/server/database/definitions.ts
// and generates dialect-specific schema files for the active database layer(s).
// Also auto-updates root server/database/schema.gen.ts to point to the active layer.
//
// Usage:
//   pnpm run db:sync                       # detect active theme & generate for its DB layer(s)
//   pnpm run db:sync -- normal             # generate only normal (MySQL)
//   pnpm run db:sync -- cloudflare         # generate only cloudflare (D1/SQLite)
//   pnpm run db:sync -- all                # generate both dialects

import { execSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import * as fs from 'node:fs'
import path from 'node:path'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const generatorPath = path.resolve(ROOT, 'packages/databases/generate-schema.ts')

const dialectMap: Record<string, string> = {
  normal: 'mysql',
  cloudflare: 'sqlite',
}

// ─── Detect active theme + its database layers ───────────────────────

function detectActiveLayers(): string[] {
  const rootConfigPath = path.resolve(ROOT, 'nuxt.config.ts')
  const rootConfig = fs.readFileSync(rootConfigPath, 'utf-8')

  // Extract the active theme path (e.g. './packages/themes/dentalis')
  const themeMatch = rootConfig.match(/extends:\s*\[\s*['"]\.\/([^'"]+)['"]/)
  if (!themeMatch) {
    console.warn('⚠  Could not detect active theme from root nuxt.config.ts — generating both dialects.')
    return ['normal', 'cloudflare']
  }

  const themeDir = path.resolve(ROOT, themeMatch[1])
  const themeConfigPath = path.resolve(themeDir, 'nuxt.config.ts')

  if (!fs.existsSync(themeConfigPath)) {
    console.warn(`⚠  Theme config not found at ${themeConfigPath} — generating both dialects.`)
    return ['normal', 'cloudflare']
  }

  const themeConfig = fs.readFileSync(themeConfigPath, 'utf-8')

  // Find all database layers in the theme's extends array
  const dbLayers: string[] = []
  const extendsMatch = themeConfig.match(/extends:\s*\[([^\]]+)\]/)
  if (extendsMatch) {
    const items = extendsMatch[1].split(',').map(s => s.trim().replace(/['"]/g, ''))
    for (const item of items) {
      if (item.includes('databases/cloudflare')) dbLayers.push('cloudflare')
      else if (item.includes('databases/normal')) dbLayers.push('normal')
    }
  }

  if (dbLayers.length === 0) {
    // Theme doesn't extend any database layer (like denti/denti-one)
    console.log('ℹ  Active theme does not extend a database layer. Generating both dialects.')
    return ['normal', 'cloudflare']
  }

  return dbLayers
}

// ─── Update root schema.gen.ts ──────────────────────────────────────

function updateRootGen(activeTarget: string): void {
  const rootGenPath = path.resolve(ROOT, 'server/database/schema.gen.ts')

  // Read the existing file to preserve export ordering
  const existing = fs.readFileSync(rootGenPath, 'utf-8')

  // Find all export lines
  const exportLines: string[] = []
  for (const line of existing.split('\n')) {
    if (line.startsWith('export const ')) exportLines.push(line)
  }

  const importPath = `../../packages/databases/${activeTarget}/server/database/schema`

  const lines: string[] = [
    '// AUTO-GENERATED FILE — DO NOT EDIT',
    '// Generated by scripts/sync-schema.ts',
    `// Active database: ${activeTarget}`,
    `// To switch database, run: pnpm run setup`,
    `import * as base from '${importPath}';`,
    '',
    ...exportLines,
    '',
  ]

  fs.writeFileSync(rootGenPath, lines.join('\n'))
  console.log(`✔  Updated root server/database/schema.gen.ts → ${activeTarget}`)
}

// ─── Main ────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2).filter(a => a !== '--').map(a => a.replace(/^--/, ''))

  let targets: string[]
  if (args.length > 0 && args[0] === 'all') {
    targets = ['normal', 'cloudflare']
  } else if (args.length > 0) {
    targets = args
  } else {
    // Auto-detect from active theme
    targets = detectActiveLayers()
  }

  // Validate
  for (const target of targets) {
    if (!dialectMap[target]) {
      console.error(`Unknown target "${target}". Valid targets: normal, cloudflare, all`)
      process.exit(1)
    }
  }

  // Generate schema for each target
  for (const target of targets) {
    const dialect = dialectMap[target]
    console.log(`\nGenerating ${target} (${dialect}) schema...`)
    execSync(`npx tsx "${generatorPath}" ${dialect}`, {
      cwd: ROOT,
      stdio: 'inherit',
    })
  }

  // Update root schema.gen.ts — choose the first target as active
  // (when both are generated, prefer cloudflare as the default)
  const activeTarget = targets.includes('cloudflare') ? 'cloudflare' : targets[0]
  updateRootGen(activeTarget)

  console.log('\n✅ Schema generation complete.')
}

main()