// AUTO-GENERATED FILE - DO NOT EDIT
import * as base from './schema';
export const blogCategories = base.blogCategories.table;
export const blogCategoriesLocales = base.blogCategoriesLocales.table;
export const blogCommentLikes = base.blogCommentLikes.table;
export const blogComments = base.blogComments.table;
export const blogPostCategories = base.blogPostCategories.table;
export const blogPosts = base.blogPosts.table;
export const blogPostsLocales = base.blogPostsLocales.table;
export const colleagues = base.colleagues.table;
export const colleaguesLocales = base.colleaguesLocales.table;
export const contactMessages = base.contactMessages.table;
export const media = base.media.table;
export const pages = base.pages.table;
export const pagesLocales = base.pagesLocales.table;
export const services = base.services.table;
export const servicesLocales = base.servicesLocales.table;
export const settings = base.settings.table;
export const testimonials = base.testimonials.table;
export const testimonialsLocales = base.testimonialsLocales.table;
export const users = base.users.table;
